# -*- coding: utf-8 -*-
"""dbcorp login detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aRk6dt3r2DHYjhdLKQifbetcGwj0fD68

# DB Corp Cybersecurity Login Analysis Dashboard (Final)

Run all cells top to bottom to launch the dashboard.
"""

!pip install streamlit pyngrok pandas plotly openpyxl

with open('app.py','w') as f:
    f.write(r'''
import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="DB Corp Cybersecurity Dashboard", layout="wide")

st.markdown("""
<style>
body {background-color:#020617;}
.banner {background:linear-gradient(90deg,#06b6d4,#3b82f6,#9333ea);padding:10px;color:white;
font-weight:bold;text-align:center;font-size:18px;border-radius:8px;margin-bottom:10px}
.footer {position:fixed;bottom:0;left:0;width:100%;background:#020617;color:white;padding:10px;
border-top:1px solid #1e293b;text-align:center;font-size:14px}
</style>
""", unsafe_allow_html=True)

st.markdown('<div class="banner"><marquee>Real-Time Cyber Threat Monitoring | Suspicious Login Detection | Security Intelligence Platform</marquee></div>', unsafe_allow_html=True)

col1,col2 = st.columns([1,6])

with col1:
    st.image("https://cdn-icons-png.flaticon.com/512/2092/2092663.png", width=100)

with col2:
    st.title("DB Corp. Ltd. Cybersecurity Operations Dashboard")

with st.sidebar:
    st.header("Menu")
    page = st.radio("Navigation",["Dashboard","Login","Signup"])

users = {"admin":"1234","analyst":"soc123"}

if page=="Login":
    st.subheader("Login")
    u = st.text_input("Username")
    p = st.text_input("Password",type="password")
    if st.button("Login"):
        if u in users and users[u]==p:
            st.success("Login successful")
        else:
            st.error("Invalid credentials")

if page=="Signup":
    st.subheader("Create Account")
    st.text_input("New Username")
    st.text_input("New Password",type="password")
    st.button("Register")

with st.expander("Dataset Requirements (Click to Expand)"):

    st.markdown("""
### Required Columns
- User ID
- Country
- ASN
- Login Successful
- Round-Trip Time [ms]
- Is Attack IP

### Optional
- Timestamp

### Cleaning Guidelines
- Remove rows with missing values
- Ensure boolean fields are True or False
- RTT must be numeric
- Country names should be consistent

### Accepted Formats
- CSV (.csv)
- Excel (.xlsx)
""")

st.header("Upload Login Dataset")

file = st.file_uploader("Upload CSV or Excel dataset",type=["csv","xlsx"])

if file is not None:

    if file.name.endswith(".csv"):
        df = pd.read_csv(file)
    else:
        df = pd.read_excel(file)

    st.subheader("Dataset Preview")
    st.dataframe(df.head())

    attack = df[df["Is Attack IP"]==True]
    failed = df[df["Login Successful"]==False]
    high_rtt = df[df["Round-Trip Time [ms]"]>500]

    col1,col2 = st.columns(2)

    with col1:
        pie = df["Login Successful"].value_counts().reset_index()
        pie.columns=["Status","Count"]
        fig = px.pie(pie,values="Count",names="Status")
        st.plotly_chart(fig,use_container_width=True)

    with col2:
        fig2 = px.histogram(df,x="Round-Trip Time [ms]")
        st.plotly_chart(fig2,use_container_width=True)

    st.subheader("Country Login Activity")

    country = df["Country"].value_counts().reset_index()
    country.columns=["Country","Count"]

    fig3 = px.bar(country,x="Country",y="Count")
    st.plotly_chart(fig3,use_container_width=True)

    c1,c2,c3 = st.columns(3)

    c1.metric("Attack IP Events",len(attack))
    c2.metric("Failed Logins",len(failed))
    c3.metric("High RTT Events",len(high_rtt))

footer = """
<div class="footer">
<b>Enterprise Cybersecurity Protection</b> | Threat monitoring - Security analytics - Incident response |
Phone: +1-800-555-0148 | Email: enterprise-security@protectionlabs.io
</div>
"""

st.markdown(footer,unsafe_allow_html=True)
''')
print('app.py created')

import os

!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
!sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

from pyngrok import ngrok
from subprocess import Popen, PIPE
import time

def run_streamlit_and_cloudflared():
    print("Starting Streamlit app in the background...")
    # Start Streamlit in the background
    streamlit_process = Popen(["streamlit", "run", "app.py"], stdout=PIPE, stderr=PIPE)
    # Give Streamlit a moment to start up
    time.sleep(5)

    print("Starting cloudflared tunnel...")
    # Start cloudflared tunnel for port 8501 (Streamlit's default port)
    cloudflared_process = Popen(["cloudflared", "tunnel", "--url", "http://localhost:8501"], stdout=PIPE, stderr=PIPE)

    # Wait a bit for the tunnel to establish and print the URL
    print("Waiting for cloudflared tunnel URL...")
    # Cloudflared usually prints the URL to stderr
    url_found = False
    for _ in range(20): # Check for 20 seconds
        line = cloudflared_process.stderr.readline().decode('utf-8').strip()
        if "https://" in line and ".trycloudflare.com" in line: # Adjust this condition based on actual cloudflared output pattern
            print(f"Cloudflared Tunnel URL: {line}")
            url_found = True
            break
        time.sleep(1)
    if not url_found:
        print("Could not find cloudflared tunnel URL. Check cloudflared output for errors.")

    print("You can now access your Streamlit app using the provided Cloudflared Tunnel URL.")
    print("The Streamlit app and cloudflared tunnel are running in the background.")
    print("To stop them, you might need to interrupt the kernel or manually kill the processes.")

    # Optionally, you might want to store these processes in a global variable
    # or return them to allow for later termination.
    global running_streamlit_process
    global running_cloudflared_process
    running_streamlit_process = streamlit_process
    running_cloudflared_process = cloudflared_process

run_streamlit_and_cloudflared()

"""After running the cell above, look for a URL starting with `https://` and ending with `.trycloudflare.com` in the output. This is your public URL to access the Streamlit dashboard.

Keep in mind that if you stop the execution of the cell where `cloudflared` is running, the tunnel will close, and the URL will become inactive.
"""